project:
  type: default
  output-dir: _output

format:
  revealjs:
    theme: [default, custom.scss]
    slide-number: true
    code-line-numbers: true
    highlight-style: github-dark
    transition: slide
    width: 1600
    height: 900
    margin: 0.1
    center: true
    hash: true
    history: true
    controls: true
    progress: true

execute:
  echo: true
  warning: false
